breadcrumbs:
    Main:
        0: Главная
        why: Почему мы?
        faq: FAQ
    Projects: Проекты
    Search: Поиск
    Users: 
        0: Пользователи
        login_page: Войти
        register_page: Регистрация
    auth:
        0: Система авторизации
        email:
            0: Через email
            reg: Регистрация
        vk: Вконтакте
    ControlPanel:
        0: Панель управления
        help_index: Помощь
        project_info: Страница проекта
        project_update: Редактирование проекта
        project_buttons: Кнопки для проекта
        server_create: Добавить сервер
application:
    mcping:
        delay: 4 hours
    robot:
        tasks:
            - owl_nuts/sentinel/QueryNext: 600
            - owl_nuts/sentinel/FillTheBoard: 1800
    vk:
        redirect_uri: http://mctop.im/auth/vk/Auth